(function(){'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={ea:!0},fa={};try{fa.__proto__=da;ca=fa.ea;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ba;
function ia(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.w=b.prototype}var ja="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function la(a,b){if(b){var c=ja;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}
la("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(p){return p};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});la("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});var I=this;function J(a){return void 0!==a}
function K(a){return"string"==typeof a}function na(a){return"number"==typeof a}function oa(){}
function pa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function M(a){return"array"==pa(a)}function qa(a){var b=pa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function N(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ra(a,b,c){return a.call.apply(a.bind,arguments)}
function sa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function ta(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ta=ra:ta=sa;return ta.apply(null,arguments)}
function ua(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function O(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.pa=function(d,e,f){for(var h=Array(arguments.length-2),p=2;p<arguments.length;p++)h[p-2]=arguments[p];return b.prototype[e].apply(d,h)}};function va(a){if(Error.captureStackTrace)Error.captureStackTrace(this,va);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.b=!0}O(va,Error);va.prototype.name="CustomError";var wa;function xa(a,b){for(var c=a.split("%s"),d="",e=c.length-1,f=0;f<e;f++)d+=c[f]+(f<b.length?b[f]:"%s");va.call(this,d+c[e]);this.a=a}O(xa,va);xa.prototype.name="AssertionError";var ya=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(K(a))return K(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},za=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=K(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Aa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=[],e=0,f=K(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var p=f[h];b.call(void 0,p,h,a)&&(d[e++]=p)}return d},Ba=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=K(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};function Da(a,b){b=ya(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}
function Ea(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Fa(a,b,c,d){Array.prototype.splice.apply(a,Ga(arguments,1))}function Ga(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Ha=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ia(a,b){if(b)a=a.replace(Ja,"&amp;").replace(Ka,"&lt;").replace(La,"&gt;").replace(Na,"&quot;").replace(Oa,"&#39;").replace(Pa,"&#0;");else{if(!Qa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ja,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ka,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(La,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Na,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Oa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Pa,"&#0;"))}return a}
var Ja=/&/g,Ka=/</g,La=/>/g,Na=/"/g,Oa=/'/g,Pa=/\x00/g,Qa=/[\x00&<>"']/;function Ra(a,b){return a<b?-1:a>b?1:0};var P;a:{var Sa=I.navigator;if(Sa){var Ta=Sa.userAgent;if(Ta){P=Ta;break a}}P=""};function Ua(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Va(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Wa(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c}function Xa(a,b){return null!==a&&b in a?a[b]:void 0}var Ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Za(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ya.length;f++)c=Ya[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function $a(a){return a=Ia(a,void 0)};function ab(a){ab[" "](a);return a}ab[" "]=oa;function bb(a,b){var c=cb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var db=-1!=P.indexOf("Opera"),Q=-1!=P.indexOf("Trident")||-1!=P.indexOf("MSIE"),eb=-1!=P.indexOf("Edge"),fb=-1!=P.indexOf("Gecko")&&!(-1!=P.toLowerCase().indexOf("webkit")&&-1==P.indexOf("Edge"))&&!(-1!=P.indexOf("Trident")||-1!=P.indexOf("MSIE"))&&-1==P.indexOf("Edge"),gb=-1!=P.toLowerCase().indexOf("webkit")&&-1==P.indexOf("Edge"),hb=-1!=P.indexOf("Macintosh");function ib(){var a=I.document;return a?a.documentMode:void 0}var jb;
a:{var kb="",lb=function(){var a=P;if(fb)return/rv:([^\);]+)(\)|;)/.exec(a);if(eb)return/Edge\/([\d\.]+)/.exec(a);if(Q)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(gb)return/WebKit\/(\S+)/.exec(a);if(db)return/(?:Version)[ \/]?(\S+)/.exec(a)}();lb&&(kb=lb?lb[1]:"");if(Q){var mb=ib();if(null!=mb&&mb>parseFloat(kb)){jb=String(mb);break a}}jb=kb}var nb=jb,cb={};
function ob(a){return bb(a,function(){for(var b=0,c=Ha(String(nb)).split("."),d=Ha(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",p=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];p=/(\d*)(\D*)(.*)/.exec(p)||["","","",""];if(0==h[0].length&&0==p[0].length)break;b=Ra(0==h[1].length?0:parseInt(h[1],10),0==p[1].length?0:parseInt(p[1],10))||Ra(0==h[2].length,0==p[2].length)||Ra(h[2],p[2]);h=h[3];p=p[3]}while(0==b)}return 0<=b})}var pb;var rb=I.document;
pb=rb&&Q?ib()||("CSS1Compat"==rb.compatMode?parseInt(nb,10):5):void 0;var sb={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};function tb(a,b){this.a=a===ub&&b||"";this.b=vb}tb.prototype.s=!0;tb.prototype.j=function(){return this.a};tb.prototype.toString=function(){return"Const{"+this.a+"}"};function wb(a){return a instanceof tb&&a.constructor===tb&&a.b===vb?a.a:"type_error:Const"}var vb={},ub={};function xb(){this.a="";this.c=null;this.b=yb}g=xb.prototype;g.s=!0;g.j=function(){return this.a.toString()};g.P=!0;g.H=function(){return 1};g.qa=function(a,b){var c=zb.exec(Ab(this).toString()),d=c[3]||"";a=c[1]+Bb("?",c[2]||"",a)+Bb("#",d,b);b=new xb;b.a=a;return b};function Ab(a){return a instanceof xb&&a.constructor===xb&&a.b===yb?a.a:"type_error:TrustedResourceUrl"}var zb=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,yb={};
function Bb(a,b,c){if(null==c)return b;if(K(c))return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=M(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b};function R(){this.a="";this.b=Cb}R.prototype.s=!0;R.prototype.j=function(){return this.a.toString()};R.prototype.P=!0;R.prototype.H=function(){return 1};function Db(a){return a instanceof R&&a.constructor===R&&a.b===Cb?a.a:"type_error:SafeUrl"}var Eb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;function Fb(a){if(a instanceof R)return a;a="object"==typeof a&&a.s?a.j():String(a);Eb.test(a)||(a="about:invalid#zClosurez");return Gb(a)}var Cb={};function Gb(a){var b=new R;b.a=a;return b}Gb("about:blank");function Hb(){this.a="";this.b=Ib}Hb.prototype.s=!0;var Ib={};Hb.prototype.j=function(){return this.a};function Jb(a){var b=new Hb;b.a=a;return b}var Kb=Jb("");
function Lb(a){if(a instanceof R)return'url("'+Db(a).toString().replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof tb)a=wb(a);else{a=String(a);var b=a.replace(Mb,"$1").replace(Mb,"$1").replace(Nb,"url");if(Ob.test(b)){if(b=!Pb.test(a)){for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}b=b&&c&&Qb(a)}a=b?Rb(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new xa("Value does not allow [{;}], got: %s.",[a]);return a}
function Qb(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&!c.test(e))return!1}return b}var Ob=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/,Nb=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,Mb=/\b(hsl|hsla|rgb|rgba|matrix|calc|minmax|fit-content|repeat|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g,Pb=/\/\*/;
function Rb(a){return a.replace(Nb,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(h,p,D){f=p;return D});b=Fb(d).j();return c+f+b+f+e})};function S(){this.a="";this.c=Sb;this.b=null}S.prototype.P=!0;S.prototype.H=function(){return this.b};S.prototype.s=!0;S.prototype.j=function(){return this.a.toString()};function Tb(a){return a instanceof S&&a.constructor===S&&a.c===Sb?a.a:"type_error:SafeHtml"}function Ub(a){if(a instanceof S)return a;var b="object"==typeof a,c=null;b&&a.P&&(c=a.H());a=Ia(b&&a.s?a.j():String(a));return T(a,c)}
var Vb=/^[a-zA-Z0-9-]+$/,Wb={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},Xb={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};
function Yb(a){if(!Vb.test("input"))throw Error("Invalid tag name <input>.");if("INPUT"in Xb)throw Error("Tag name <input> is not allowed for SafeHtml.");var b=null,c="";if(a)for(D in a){if(!Vb.test(D))throw Error('Invalid attribute name "'+D+'".');var d=a[D];if(null!=d){var e=D;var f=d;if(f instanceof tb)f=wb(f);else if("style"==e.toLowerCase()){d=void 0;if(!N(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof
Hb)){var h="";for(d in f){if(!/^[-_a-zA-Z0-9]+$/.test(d))throw Error("Name allows only [-_a-zA-Z0-9], got: "+d);var p=f[d];null!=p&&(p=M(p)?Ba(p,Lb).join(" "):Lb(p),h+=d+":"+p+";")}f=h?Jb(h):Kb}f=f instanceof Hb&&f.constructor===Hb&&f.b===Ib?f.a:"type_error:SafeStyle"}else{if(/^on/i.test(e))throw Error('Attribute "'+e+'" requires goog.string.Const value, "'+f+'" given.');if(e.toLowerCase()in Wb)if(f instanceof xb)f=Ab(f).toString();else if(f instanceof R)f=Db(f).toString();else if(K(f))f=Fb(f).j();
else throw Error('Attribute "'+e+'" on tag "input" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+f+'" given.');}f.s&&(f=f.j());e=e+'="'+Ia(String(f))+'"';c+=" "+e}}var D="<input"+c;c=void 0;null!=c?M(c)||(c=[c]):c=[];!0===sb.input?D+=">":(b=Zb(c),D+=">"+Tb(b).toString()+"</input>",b=b.H());(a=a&&a.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?b=0:b=null);return T(D,b)}
function Zb(a){function b(e){M(e)?za(e,b):(e=Ub(e),d+=Tb(e).toString(),e=e.H(),0==c?c=e:0!=e&&c!=e&&(c=null))}var c=0,d="";za(arguments,b);return T(d,c)}var Sb={};function T(a,b){var c=new S;c.a=a;c.b=b;return c}T("<!DOCTYPE html>",0);var $b=T("",0),ac=T("<br>",0);var bc="StopIteration"in I?I.StopIteration:{message:"StopIteration",stack:""};function cc(){}cc.prototype.next=function(){throw bc;};cc.prototype.G=function(){return this};function dc(a){if(a instanceof cc)return a;if("function"==typeof a.G)return a.G(!1);if(qa(a)){var b=0,c=new cc;c.next=function(){for(;;){if(b>=a.length)throw bc;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function ec(a,b){if(qa(a))try{za(a,b,void 0)}catch(c){if(c!==bc)throw c;}else{a=dc(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==bc)throw c;}}}function fc(a){if(qa(a))return Ea(a);a=dc(a);var b=[];ec(a,function(c){b.push(c)});return b};var gc={},hc={},ic={};function jc(){throw Error("Do not instantiate directly");}jc.prototype.c=null;jc.prototype.toString=function(){return this.b};jc.prototype.f=function(){if(this.a===ic)return Ub(this.toString());if(this.a!==gc)throw Error("Sanitized content was not of kind TEXT or HTML.");return T(this.toString(),this.c||null)};jc.prototype.h=function(){if(this.a!==hc)throw Error("Sanitized content was not of kind URI.");return Gb(this.toString())};function kc(){jc.call(this)}O(kc,jc);
kc.prototype.a=gc;var lc=function(a){function b(c){this.b=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.c=d);return c}}(kc),mc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function nc(a){return mc[a]}var oc=/[\x00\x22\x27\x3c\x3e]/g;/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(l){return l.replace(Dc,"&amp;").replace(Ec,"&lt;").replace(Fc,"&gt;")}function b(l,r,u){switch(l.nodeType){case 1:var w=l.tagName.toLowerCase();r.push("<",w);var z=l.attributes,H=z.length;if(H){if(u){for(var C=[],x=H;0<=--x;)C[x]=z[x];C.sort(function(v,E){return v.name<E.name?-1:v.name===E.name?0:1});z=C}for(x=0;x<H;++x)C=z[x],C.specified&&r.push(" ",C.name.toLowerCase(),'="',C.value.replace(Dc,"&amp;").replace(Ec,"&lt;").replace(Fc,"&gt;").replace(ae,"&quot;"),'"')}r.push(">");
for(z=l.firstChild;z;z=z.nextSibling)b(z,r,u);!l.firstChild&&/^(?:br|link|img)$/.test(w)||r.push("</",w,">");break;case 3:case 4:r.push(a(l.nodeValue))}}function c(l){function r(m){if("\\"!==m.charAt(0))return m.charCodeAt(0);switch(m.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(m.substring(2),16)||m.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(m.substring(1),
8);default:return m.charCodeAt(1)}}function u(m){if(32>m)return(16>m?"\\x0":"\\x")+m.toString(16);m=String.fromCharCode(m);if("\\"===m||"-"===m||"["===m||"]"===m)m="\\"+m;return m}function w(m){var n=m.substring(1,m.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);m=[];for(var k=[],A="^"===n[0],q=A?1:0,y=n.length;q<y;++q){var t=n[q];switch(t){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":m.push(t);continue}t=
r(t);if(q+2<y&&"-"===n[q+1]){var G=r(n[q+2]);q+=2}else G=t;k.push([t,G]);65>G||122<t||(65>G||90<t||k.push([Math.max(65,t)|32,Math.min(G,90)|32]),97>G||122<t||k.push([Math.max(97,t)&-33,Math.min(G,122)&-33]))}k.sort(function(L,ea){return L[0]-ea[0]||ea[1]-L[1]});n=[];t=[NaN,NaN];for(q=0;q<k.length;++q)y=k[q],y[0]<=t[1]+1?t[1]=Math.max(t[1],y[1]):n.push(t=y);k=["["];A&&k.push("^");k.push.apply(k,m);for(q=0;q<n.length;++q)y=n[q],k.push(u(y[0])),y[1]>y[0]&&(y[1]+1>y[0]&&k.push("-"),k.push(u(y[1])));k.push("]");
return k.join("")}function z(m){for(var n=m.source.match(/(?:\[(?:[^\x5C\x5D]|\\[\s\S])*\]|\\u[A-Fa-f0-9]{4}|\\x[A-Fa-f0-9]{2}|\\[0-9]+|\\[^ux0-9]|\(\?[:!=]|[\(\)\^]|[^\x5B\x5C\(\)\^]+)/g),k=n.length,A=[],q=0,y=0;q<k;++q){var t=n[q];"("===t?++y:"\\"===t.charAt(0)&&(t=+t.substring(1))&&t<=y&&(A[t]=-1)}for(q=1;q<A.length;++q)-1===A[q]&&(A[q]=++H);for(y=q=0;q<k;++q)t=n[q],"("===t?(++y,void 0===A[y]&&(n[q]="(?:")):"\\"===t.charAt(0)&&(t=+t.substring(1))&&t<=y&&(n[q]="\\"+A[y]);for(y=q=0;q<k;++q)"^"===
n[q]&&"^"!==n[q+1]&&(n[q]="");if(m.ignoreCase&&C)for(q=0;q<k;++q)t=n[q],m=t.charAt(0),2<=t.length&&"["===m?n[q]=w(t):"\\"!==m&&(n[q]=t.replace(/[a-zA-Z]/g,function(G){G=G.charCodeAt(0);return"["+String.fromCharCode(G&-33,G|32)+"]"}));return n.join("")}for(var H=0,C=!1,x=!1,v=0,E=l.length;v<E;++v){var F=l[v];if(F.ignoreCase)x=!0;else if(/[a-z]/i.test(F.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){C=!0;x=!1;break}}var B=[];v=0;for(E=l.length;v<E;++v){F=l[v];if(F.global||F.multiline)throw Error(""+
F);B.push("(?:"+z(F)+")")}return new RegExp(B.join("|"),x?"gi":"g")}function d(l){var r=0;return function(u){for(var w=null,z=0,H=0,C=u.length;H<C;++H)switch(u.charAt(H)){case "\t":w||(w=[]);w.push(u.substring(z,H));z=l-r%l;for(r+=z;0<=z;z-=16)w.push("                ".substring(0,z));z=H+1;break;case "\n":r=0;break;default:++r}if(!w)return u;w.push(u.substring(z));return w.join("")}}function e(l,r,u,w){r&&(l={source:r,V:l},u(l),w.push.apply(w,l.W))}function f(l,r){function u(C){for(var x=C.V,v=[x,
"pln"],E=0,F=C.source.match(z)||[],B={},m=0,n=F.length;m<n;++m){var k=F[m],A=B[k],q=void 0;if("string"===typeof A)var y=!1;else{var t=w[k.charAt(0)];if(t)q=k.match(t[1]),A=t[0];else{for(y=0;y<H;++y)if(t=r[y],q=k.match(t[1])){A=t[0];break}q||(A="pln")}!(y=5<=A.length&&"lang-"===A.substring(0,5))||q&&"string"===typeof q[1]||(y=!1,A="src");y||(B[k]=A)}t=E;E+=k.length;if(y){y=q[1];var G=k.indexOf(y),L=G+y.length;q[2]&&(L=k.length-q[2].length,G=L-y.length);A=A.substring(5);e(x+t,k.substring(0,G),u,v);
e(x+t+G,y,Ca(A,y),v);e(x+t+L,k.substring(L),u,v)}else v.push(x+t,A)}C.W=v}var w={},z;(function(){for(var C=l.concat(r),x=[],v={},E=0,F=C.length;E<F;++E){var B=C[E],m=B[3];if(m)for(var n=m.length;0<=--n;)w[m.charAt(n)]=B;B=B[1];m=""+B;v.hasOwnProperty(m)||(x.push(B),v[m]=null)}x.push(/[\0-\uffff]/);z=c(x)})();var H=r.length;return u}function h(l){var r=[],u=[];l.tripleQuotedStrings?r.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):l.multiLineStrings?r.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):r.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);l.verbatimStrings&&u.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var w=l.hashComments;w&&(l.cStyleComments?(1<w?r.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):r.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),u.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):r.push(["com",/^#[^\r\n]*/,null,"#"]));l.cStyleComments&&(u.push(["com",/^\/\/[^\r\n]*/,null]),u.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));l.regexLiterals&&u.push(["lang-regex",new RegExp("^"+be+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);l=l.keywords.replace(/^\s+|\s+$/g,"");l.length&&u.push(["kwd",new RegExp("^(?:"+l.replace(/\s+/g,
"|")+")\\b"),null]);r.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);u.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(r,u)}function p(l){function r(ma){if(ma>v){E&&E!==F&&(x.push("</span>"),E=null);!E&&F&&(E=F,x.push('<span class="',E,'">'));var Gc=a(n(u.substring(v,ma))).replace(t?
A:k,"$1&#160;");t=y.test(Gc);x.push(Gc.replace(q,Hc));v=ma}}var u=l.source,w=l.fa,z=l.W,H=l.$,C=l.ca,x=[],v=0,E=null,F=null,B=0,m=0,n=d(window.PR_TAB_WIDTH),k=/([\r\n ]) /g,A=/(^| ) /gm,q=/\r\n?|\n/g,y=/[ \r\n]$/,t=!0,G=window._pr_isIE6();C=G?C&&"PRE"===C.tagName?6===G?"&#160;\r\n":7===G?"&#160;<br />\r":8===G?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(H){var L=[];for(G=0;10>G;++G)L[G]=C+'</li><li class="L'+G+'">';var ea="number"===typeof H?H-1:0;x.push('<ol class="linenums"><li class="L',
ea%10,'"');ea&&x.push(' value="',ea+1,'"');x.push(">");var Hc=function(){var ma=L[++ea%10];return E?"</span>"+ma+'<span class="'+E+'">':ma}}else Hc=C;for(;;)if(B<w.length&&(m<z.length?w[B]<=z[m]:1))r(w[B]),E&&(x.push("</span>"),E=null),x.push(w[B+1]),B+=2;else if(m<z.length)r(z[m]),F=z[m+1],m+=2;else break;r(u.length);E&&x.push("</span>");H&&x.push("</li></ol>");l.R=x.join("")}function D(l,r){for(var u=r.length;0<=--u;){var w=r[u];Ma.hasOwnProperty(w)?"console"in window&&console.warn("cannot override language handler %s",
w):Ma[w]=l}}function Ca(l,r){l&&Ma.hasOwnProperty(l)||(l=/^\s*</.test(r)?"default-markup":"default-code");return Ma[l]}function Ic(l){var r=l.ba,u=l.Z;l.R=r;try{var w=r.match(ce);r=[];var z=0,H=[];if(w)for(var C=0,x=w.length;C<x;++C){var v=w[C];if(1<v.length&&"<"===v.charAt(0)){if(!de.test(v))if(ee.test(v))r.push(v.substring(9,v.length-3)),z+=v.length-12;else if(fe.test(v))r.push("\n"),++z;else if(0<=v.indexOf("nocode")&&v.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var E=
v.match(Jc)[2],F=1;var B=C+1;a:for(;B<x;++B){var m=w[B].match(Jc);if(m&&m[2]===E)if("/"===m[1]){if(0===--F)break a}else++F}B<x?(H.push(z,w.slice(C,B+1).join("")),C=B):H.push(z,v)}else H.push(z,v)}else{F=v;var n=F.indexOf("&");if(0>n)var k=F;else{for(--n;0<=(n=F.indexOf("&#",n+1));){var A=F.indexOf(";",n);if(0<=A){var q=F.substring(n+3,A),y=10;q&&"x"===q.charAt(0)&&(q=q.substring(1),y=16);var t=parseInt(q,y);isNaN(t)||(F=F.substring(0,n)+String.fromCharCode(t)+F.substring(A+1))}}k=F.replace(ge,"<").replace(he,
">").replace(ie,"'").replace(je,'"').replace(ke," ").replace(le,"&")}r.push(k);z+=k.length}}var G=r.join("");l.source=G;l.V=0;l.fa=H;Ca(u,G)(l);p(l)}catch(L){"console"in window&&console.log(L&&L.stack?L.stack:L)}}var be=function(){for(var l="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),r="(?:^^|[+-]",u=0;u<l.length;++u)r+=
"|"+l[u].replace(/([^=<>:&a-z])/g,"\\$1");return r+")\\s*"}(),Dc=/&/g,Ec=/</g,Fc=/>/g,ae=/"/g,ge=/&lt;/g,he=/&gt;/g,ie=/&apos;/g,je=/&quot;/g,le=/&amp;/g,ke=/&nbsp;/g,me=/[\r\n]/g,qb=null,ce=/[^<]+|\x3c!--[\s\S]*?--\x3e|<!\[CDATA\[[\s\S]*?\]\]>|<\/?[a-zA-Z](?:[^>"']|'[^']*'|"[^"]*")*>|</g,de=/^\x3c!--/,ee=/^<!\[CDATA\[/,fe=/^<br\b/i,Jc=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,ne=h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Ma={};D(ne,["default-code"]);D(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));D(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);D(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));D(h({keywords:"null true false"}),["json"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);D(h({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);D(h({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);D(h({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);D(h({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);D(h({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);D(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(l,r,u){l={ba:l,Z:r,$:u};Ic(l);return l.R};window.prettyPrint=function(l){function r(){for(var F=
window.PR_SHOULD_USE_CONTINUATION?x.now()+250:Infinity;v<w.length&&x.now()<F;v++){var B=w[v];if(B.className&&0<=B.className.indexOf("prettyprint")){var m=B.className.match(/\blang-(\w+)\b/);m&&(m=m[1]);for(var n=!1,k=B.parentNode;k;k=k.parentNode)if(("pre"===k.tagName||"code"===k.tagName||"xmp"===k.tagName)&&k.className&&0<=k.className.indexOf("prettyprint")){n=!0;break}if(!n){k=B;null===qb&&(n=document.createElement("PRE"),n.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
qb=!/</.test(n.innerHTML));if(qb)if(n=k.innerHTML,"XMP"===k.tagName)n=a(n);else{if("PRE"!==k.tagName&&me.test(n)){var A="";k.currentStyle?A=k.currentStyle.whiteSpace:window.getComputedStyle&&(A=window.getComputedStyle(k,null).whiteSpace);k=!A||"pre"===A}else k=!0;k||(n=n.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{n=[];for(k=k.firstChild;k;k=k.nextSibling)b(k,n);n=n.join("")}n=n.replace(/(?:\r\n?|\n)$/,"");k=B.className.match(/\blinenums\b(?::(\d+))?/);E={ba:n,Z:m,
ca:B,$:k?k[1]&&k[1].length?+k[1]:!0:!1};Ic(E);if(B=E.R)if(m=E.ca,"XMP"===m.tagName){n=document.createElement("PRE");for(k=0;k<m.attributes.length;++k)A=m.attributes[k],A.specified&&("class"===A.name.toLowerCase()?n.className=A.value:n.setAttribute(A.name,A.value));n.innerHTML=B;m.parentNode.replaceChild(n,m)}else m.innerHTML=B}}}v<w.length?setTimeout(r,250):l&&l()}for(var u=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],w=[],z=0;z<
u.length;++z)for(var H=0,C=u[z].length;H<C;++H)w.push(u[z][H]);u=null;var x=Date;x.now||(x={now:function(){return(new Date).getTime()}});var v=0,E;r()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:D,sourceDecorator:h,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof)\b/],[PR.PR_LITERAL,/^(?:true|false|null)\b/],
[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);function pc(){return lc('<div class="devsite-code-buttons-container"></div>')}function qc(){var a='<button class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" title="'+"Dark code theme".replace(oc,nc);return lc(a+'"></button>')}
function rc(){var a='<button class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" title="'+"Light code theme".replace(oc,nc);return lc(a+'"></button>')}
function sc(){var a='<button class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" title="'+"\u6309\u9019\u88e1\u8907\u88fd".replace(oc,nc);return lc(a+'"></button>')}
function tc(){var a='<button class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" title="'+"\u5728 JSFiddle \u4e2d\u958b\u555f".replace(oc,nc);return lc(a+'"></button>')};function uc(a){var b=HTMLElement.call(this)||this;a&&(K(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ia(uc,HTMLElement);g=uc.prototype;g.connectedCallback=function(){vc(this)};g.X=function(){return""};function vc(a){var b=a.X();!a.hasAttribute("ds-is")&&b&&a.setAttribute("ds-is",b)}g.uc=function(){console.warn(this.tagName,"has not implemented update")};
g.sa=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};g.ac=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};uc.prototype.connectedCallback=uc.prototype.connectedCallback;var wc=!Q||9<=Number(pb),xc=!fb&&!Q||Q&&9<=Number(pb)||fb&&ob("1.9.1"),yc=Q&&!ob("9"),zc=Q||db||gb;var Ac=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=Tb($b);return!b.parentElement});function Bc(a,b){if(Ac())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=Tb(b)}function Cc(a,b){Bc(a,b)};function Kc(a,b){this.a=J(a)?a:0;this.b=J(b)?b:0}g=Kc.prototype;g.Bb=function(){return new Kc(this.a,this.b)};g.va=function(a){return a instanceof Kc&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.Db=function(a,b){a instanceof Kc?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),na(b)&&(this.b+=b));return this};g.Cb=function(a,b){b=na(b)?b:a;this.a*=a;this.b*=b;return this};g.gc=function(a,b){a=a*Math.PI/180;b=b||new Kc(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Lc(a,b){this.width=a;this.height=b}g=Lc.prototype;g.Eb=function(){return new Lc(this.width,this.height)};g.Va=function(){return Math.max(this.width,this.height)};g.ib=function(){return Math.min(this.width,this.height)};g.bc=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.Pb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.za=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Mc(a,b){var c=na(void 0)?void 0:b;a.width*=b;a.height*=c;return a}g.ic=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Mc(this,a)};
g.jc=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Mc(this,a)};function Nc(a){return a?new Oc(U(a)):wa||(wa=new Oc)}function Pc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Qc(document,"*",a,b);return d||null}
function Rc(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var p;if(p="function"==typeof e.split)p=0<=ya(e.split(/\s+/),c);p&&(a[d++]=h)}a.length=d;return a}return b}
function Qc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Rc(a,b,c,d)[0]||null}function Sc(a,b){Ua(b,function(c,d){c&&"object"==typeof c&&c.s&&(c=c.j());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Tc.hasOwnProperty(d)?a.setAttribute(Tc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Tc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Uc(a){a=a.document;a=Vc(a)?a.documentElement:a.body;return new Lc(a.clientWidth,a.clientHeight)}function Wc(a){return a.scrollingElement?a.scrollingElement:!gb&&Vc(a)?a.documentElement:a.body||a.documentElement}
function Xc(a){return a.parentWindow||a.defaultView}function Yc(a,b,c,d){function e(h){h&&b.appendChild(K(h)?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];qa(f)&&!Zc(f)?za($c(f)?Ea(f):f,e):e(f)}}function V(a,b){return a.createElement(String(b))}function Vc(a){return"CSS1Compat"==a.compatMode}function ad(a){for(var b;b=a.firstChild;)a.removeChild(b)}function bd(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}
function cd(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Zc(a){return N(a)&&0<a.nodeType}function dd(a){return N(a)&&1==a.nodeType}function ed(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function fd(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return gd(b,a)}function gd(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function U(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function hd(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else ad(a),a.appendChild(U(a).createTextNode(String(b)))}function id(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||id(a,b,c,d))return!0;a=a.nextSibling}return!1}var jd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},kd={IMG:" ",BR:"\n"};
function ld(a){return md(a)&&nd(a)}function md(a){return Q&&!ob("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function nd(a){a=a.tabIndex;return na(a)&&0<=a&&32768>a}function od(a){if(yc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];pd(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");yc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function pd(a,b,c){if(!(a.nodeName in jd))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in kd)b.push(kd[a.nodeName]);else for(a=a.firstChild;a;)pd(a,b,c),a=a.nextSibling}function $c(a){if(a&&"number"==typeof a.length){if(N(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==pa(a))return"function"==typeof a.item}return!1}
function qd(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return rd(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h=K(f.className))&&(f=f.className.split(/\s+/),h=0<=ya(f,c));return h},!0,d)}function rd(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function Oc(a){this.a=a||I.document||document}g=Oc.prototype;g.pb=Nc;g.kc=function(a){this.a=a};g.o=function(a){return K(a)?this.a.getElementById(a):a};
g.hb=function(a){return K(a)?this.a.getElementById(a):a};g.ka=Oc.prototype.o;g.qb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.ha=function(a,b,c){return Rc(this.a,a,b,c)};g.Na=function(a,b,c){return Qc(this.a,a,b,c)};g.rb=function(a,b){return Pc(a,b||this.a)};g.la=Oc.prototype.ha;g.pc=Sc;g.kb=function(a){return Uc(a||Xc(this.a)||window)};
g.Ja=function(){var a=Xc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Uc(a).height,Vc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.Y=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!wc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',$a(h.name),'"');if(h.type){f.push(' type="',$a(h.type),'"');var p={};Za(p,h);delete p.type;h=p}f.push(">");f=f.join("")}f=d.createElement(f);h&&(K(h)?f.className=h:M(h)?f.className=h.join(" "):Sc(f,h));2<e.length&&Yc(d,f,e,2);return f};g.ma=Oc.prototype.Y;g.ob=function(a){return this.a.createTextNode(String(a))};
g.ta=function(a,b,c){var d=this.a;c=!!c;for(var e=V(d,"TABLE"),f=e.appendChild(V(d,"TBODY")),h=0;h<a;h++){for(var p=V(d,"TR"),D=0;D<b;D++){var Ca=V(d,"TD");c&&hd(Ca,"\u00a0");p.appendChild(Ca)}f.appendChild(p)}return e};g.hc=function(a){var b=this.a;var c=V(b,"DIV");Q?(a=Zb(ac,a),Bc(c,a),c.removeChild(c.firstChild)):Bc(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.Nb=function(){return Vc(this.a)};
g.La=function(){return Wc(this.a)};g.Ka=function(){var a=this.a,b=Wc(a);a=Xc(a);return Q&&ob("10")&&a.pageYOffset!=b.scrollTop?new Kc(b.scrollLeft,b.scrollTop):new Kc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.Ba=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.mb=function(a,b){a.appendChild(b)};g.lb=function(a,b){Yc(U(a),a,arguments,1)};g.nb=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.sb=ad;g.Lb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.Kb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.Jb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.tb=bd;g.ub=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.Aa=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return bd(a)}};
g.Ha=function(a){return xc&&void 0!=a.children?a.children:Aa(a.childNodes,function(b){return 1==b.nodeType})};g.Pa=function(a){return J(a.firstElementChild)?a.firstElementChild:cd(a.firstChild,!0)};g.Ua=function(a){return J(a.lastElementChild)?a.lastElementChild:cd(a.lastChild,!1)};g.Xa=function(a){return J(a.nextElementSibling)?a.nextElementSibling:cd(a.nextSibling,!0)};g.fb=function(a){return J(a.previousElementSibling)?a.previousElementSibling:cd(a.previousSibling,!1)};
g.Ya=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.gb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.Sb=Zc;g.Ob=dd;g.Vb=function(a){return N(a)&&a.window==a};g.eb=function(a){var b;if(zc&&!(Q&&ob("9")&&!ob("10")&&I.SVGElement&&a instanceof I.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return dd(b)?b:null};
g.contains=ed;
g.ra=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(Q&&!(9<=Number(pb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?gd(a,b):!c&&ed(e,b)?-1*fd(a,b):!d&&ed(f,a)?fd(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=U(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(I.Range.START_TO_END,a)};g.wa=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var p=1;p<c;p++)if(h!=d[p][b])return f;f=h}return f};g.cb=U;g.Ra=function(a){return a.contentDocument||a.contentWindow.document};
g.Sa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Xc(c):window}else d=null;b=d}return b}catch(e){}return null};g.sc=hd;g.bb=function(a){if("outerHTML"in a)return a.outerHTML;var b=V(U(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.xa=function(a,b){var c=[];return id(a,b,c,!0)?c[0]:void 0};g.ya=function(a,b){var c=[];id(a,b,c,!1);return c};g.Rb=ld;g.lc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.Qb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!md(a)||nd(a)):ld(a))&&Q){var c;"function"!=pa(a.getBoundingClientRect)||Q&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.jb=od;g.$a=function(a){return od(a).length};
g.ab=function(a,b){b=b||U(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(od(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Za=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in jd))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in kd)d+=kd[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);N(c)&&(c.ec=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.Tb=$c;g.Ea=qd;g.Da=function(a,b,c){return qd(a,null,b,c)};g.Ca=rd;g.Fa=function(a){return a.getContext("2d")};function sd(){var a=void 0===a?document:a;return a.querySelector('[ds-is="snackbar"]')};function td(a,b){window.getSelection().removeAllRanges();var c=document.createElement("pre");c.style.position="absolute";c.style.top="-99999px";c.style.left="-99999px";Array.from(b.childNodes).forEach(function(d){d.classList&&d.classList.contains("no-select")||c.appendChild(d.cloneNode(!0))});a.appendChild(c);return c}function ud(a){window.getSelection().selectAllChildren(a);return window.getSelection().toString()}
function vd(a,b){a=td(a,b);b=!1;ud(a)&&document.queryCommandSupported("copy")&&(document.execCommand("copy"),b=!0);window.getSelection().removeAllRanges();bd(a);return b}function wd(a,b){var c=document.createElement("pre");b.forEach(function(d){c.appendChild(d.cloneNode(!0))});b=sd();vd(a,c)&&b&&b.setAttribute("type","copied-to-clipboard");bd(c)};function xd(){this.B=this.B;this.m=this.m}g=xd.prototype;g.B=!1;g.ja=function(){return this.B};g.Ia=xd.prototype.ja;g.K=function(){this.B||(this.B=!0,this.A())};g.dc=function(a){a=ua(yd,a);this.B?J(void 0)?a.call(void 0):a():(this.m||(this.m=[]),this.m.push(J(void 0)?ta(a,void 0):a))};g.A=function(){if(this.m)for(;this.m.length;)this.m.shift()()};function yd(a){a&&"function"==typeof a.K&&a.K()};var zd=!Q||9<=Number(pb),Ad=!Q||9<=Number(pb),Bd=Q&&!ob("9"),Cd=function(){if(!I.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{I.addEventListener("test",oa,b),I.removeEventListener("test",oa,b)}catch(c){}return a}();function Dd(a,b){this.type=a;this.b=this.target=b;this.F=this.c=!1;this.aa=!0}Dd.prototype.h=function(){this.c=!0};Dd.prototype.f=function(){this.F=!0;this.aa=!1};function W(a,b){Dd.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.v=this.m=0;this.key="";this.i=this.l=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.C=null;this.I=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(fb){a:{try{ab(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.m=gb||void 0!==a.offsetX?a.offsetX:a.layerX,this.v=gb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.l=a.keyCode||0;this.key=a.key||"";this.i=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.I=hb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=K(a.pointerType)?a.pointerType:Ed[a.pointerType]||"";this.C=a.state;this.a=a;a.defaultPrevented&&this.f()}}O(W,Dd);var Fd=[1,4,2],Ed={2:"touch",3:"pen",4:"mouse"};
W.prototype.T=function(){return(zd?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Fd[0]))&&!(gb&&hb&&this.ctrlKey)};W.prototype.h=function(){W.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};W.prototype.f=function(){W.w.f.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Bd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};W.prototype.N=function(){return this.a};var Gd="closure_listenable_"+(1E6*Math.random()|0);function Hd(a){return!(!a||!a[Gd])}var Id=0;function Jd(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.L=e;this.key=++Id;this.D=this.J=!1}function Kd(a){a.D=!0;a.listener=null;a.a=null;a.src=null;a.L=null};function Ld(a){this.src=a;this.a={};this.b=0}Ld.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};Ld.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Md(a,b,d,e);-1<h?(b=a[h],c||(b.J=!1)):(b=new Jd(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};
Ld.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Md(e,b,c,d);return-1<b?(Kd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};function Nd(a,b){var c=b.type;c in a.a&&Da(a.a[c],b)&&(Kd(b),0==a.a[c].length&&(delete a.a[c],a.b--))}function Od(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Md(a,c,d,e));return-1<b?a[b]:null}
function Pd(a,b,c){var d=J(b),e=d?b.toString():"",f=J(c);return Va(a.a,function(h){for(var p=0;p<h.length;++p)if(!(d&&h[p].type!=e||f&&h[p].capture!=c))return!0;return!1})}function Md(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.D&&f.listener==b&&f.capture==!!c&&f.L==d)return e}return-1};var Qd="closure_lm_"+(1E6*Math.random()|0),Rd={},Sd=0;function Td(a,b,c,d,e){if(d&&d.once)return Ud(a,b,c,d,e);if(M(b)){for(var f=0;f<b.length;f++)Td(a,b[f],c,d,e);return null}c=Vd(c);return Hd(a)?a.u(b,c,N(d)?!!d.capture:!!d,e):Wd(a,b,c,!1,d,e)}
function Wd(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=N(e)?!!e.capture:!!e,p=Xd(a);p||(a[Qd]=p=new Ld(a));c=p.add(b,c,d,h,f);if(c.a)return c;d=Yd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Cd||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Zd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Sd++;return c}
function Yd(){var a=$d,b=Ad?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Ud(a,b,c,d,e){if(M(b)){for(var f=0;f<b.length;f++)Ud(a,b[f],c,d,e);return null}c=Vd(c);return Hd(a)?a.h.add(String(b),c,!0,N(d)?!!d.capture:!!d,e):Wd(a,b,c,!0,d,e)}function oe(a,b,c,d,e){if(M(b))for(var f=0;f<b.length;f++)oe(a,b[f],c,d,e);else d=N(d)?!!d.capture:!!d,c=Vd(c),Hd(a)?a.M(b,c,d,e):a&&(a=Xd(a))&&(b=Od(a,b,c,d,e))&&pe(b)}
function pe(a){if(!na(a)&&a&&!a.D){var b=a.src;if(Hd(b))Nd(b.h,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Zd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Sd--;(c=Xd(b))?(Nd(c,a),0==c.b&&(c.src=null,b[Qd]=null)):Kd(a)}}}function Zd(a){return a in Rd?Rd[a]:Rd[a]="on"+a}
function qe(a,b,c,d){var e=!0;if(a=Xd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.D&&(f=re(f,d),e=e&&!1!==f)}return e}function re(a,b){var c=a.listener,d=a.L||a.src;a.J&&pe(a);return c.call(d,b)}
function $d(a,b){if(a.D)return!0;if(!Ad){if(!b)a:{b=["window","event"];for(var c=I,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new W(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var f=qe(d[e],a,!0,b);c=c&&f}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],f=qe(d[e],a,!1,b),c=
c&&f}return c}return re(a,new W(b,this))}function Xd(a){a=a[Qd];return a instanceof Ld?a:null}var se="__closure_events_fn_"+(1E9*Math.random()>>>0);function Vd(a){if("function"==pa(a))return a;a[se]||(a[se]=function(b){return a.handleEvent(b)});return a[se]};function te(a){xd.call(this);this.b=a;this.a={}}O(te,xd);var ue=[];g=te.prototype;g.u=function(a,b,c,d){return ve(this,a,b,c,d)};g.Xb=function(a,b,c,d,e){return ve(this,a,b,c,d,e)};function ve(a,b,c,d,e,f){M(c)||(c&&(ue[0]=c.toString()),c=ue);for(var h=0;h<c.length;h++){var p=Td(b,c[h],d||a.handleEvent,e||!1,f||a.b||a);if(!p)break;a.a[p.key]=p}return a}g.wb=function(a,b,c,d){return we(this,a,b,c,d)};g.Wb=function(a,b,c,d,e){return we(this,a,b,c,d,e)};
function we(a,b,c,d,e,f){if(M(c))for(var h=0;h<c.length;h++)we(a,b,c[h],d,e,f);else{b=Ud(b,c,d||a.handleEvent,e,f||a.b||a);if(!b)return a;a.a[b.key]=b}return a}g.Yb=function(a,b,c,d){b.u(a,c,d,this.b||this);return this};g.Zb=function(a,b,c,d,e){b.u(a,c,d,e||this.b||this);return this};g.vb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
g.M=function(a,b,c,d,e){if(M(b))for(var f=0;f<b.length;f++)this.M(a,b[f],c,d,e);else c=c||this.handleEvent,d=N(d)?!!d.capture:!!d,e=e||this.b||this,c=Vd(c),d=!!d,b=Hd(a)?Od(a.h,String(b),c,d,e):a?(a=Xd(a))?Od(a,b,c,d,e):null:null,b&&(pe(b),delete this.a[b.key])};g.tc=function(a,b,c,d,e){b.M(a,c,d,e||this.b||this,this);return this};function xe(a){Ua(a.a,function(b,c){this.a.hasOwnProperty(c)&&pe(b)},a);a.a={}}g.A=function(){te.w.A.call(this);xe(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function ye(a){var b=a(ze,void 0,void 0);a=V(Nc().a,"DIV");b=Ae(b);Bc(a,T(b,null));1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}function Ae(a){if(!N(a))return String(a);if(a instanceof jc){if(a.a===gc)return a.b;if(a.a===ic)return $a(a.b)}return"zSoyz"}var ze={};function Be(){};function Ce(){}O(Ce,Be);Ce.prototype.ga=function(){var a=0;ec(this.G(!0),function(){a++});return a};Ce.prototype.ia=function(){var a=fc(this.G(!0)),b=this;za(a,function(c){b.remove(c)})};function De(a){this.a=a}O(De,Ce);g=De.prototype;g.Mb=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};g.get=function(a){a=this.a.getItem(a);if(!K(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};g.remove=function(a){this.a.removeItem(a)};
g.ga=function(){return this.a.length};g.G=function(a){var b=0,c=this.a,d=new cc;d.next=function(){if(b>=c.length)throw bc;var e=c.key(b++);if(a)return e;e=c.getItem(e);if(!K(e))throw"Storage mechanism: Invalid value was encountered";return e};return d};g.ia=function(){this.a.clear()};g.key=function(a){return this.a.key(a)};function Ee(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}O(Ee,De);function Fe(){xd.call(this);this.h=new Ld(this);this.T=this;this.C=null}O(Fe,xd);Fe.prototype[Gd]=!0;g=Fe.prototype;g.S=function(a){this.C=a};g.xb=function(a,b,c,d){Td(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){oe(this,a,b,c,d)};
g.yb=function(a){var b,c=this.C;if(c)for(b=[];c;c=c.C)b.push(c);c=this.T;var d=a.type||a;if(K(a))a=new Dd(a,c);else if(a instanceof Dd)a.target=a.target||c;else{var e=a;a=new Dd(d,c);Za(a,e)}e=!0;if(b)for(var f=b.length-1;!a.c&&0<=f;f--){var h=a.b=b[f];e=Ge(h,d,!0,a)&&e}a.c||(h=a.b=c,e=Ge(h,d,!0,a)&&e,a.c||(e=Ge(h,d,!1,a)&&e));if(b)for(f=0;!a.c&&f<b.length;f++)h=a.b=b[f],e=Ge(h,d,!1,a)&&e;return e};
g.A=function(){Fe.w.A.call(this);if(this.h){var a=this.h,b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,Kd(d[e]);delete a.a[c];a.b--}}this.C=null};g.u=function(a,b,c,d){return this.h.add(String(a),b,!1,c,d)};g.M=function(a,b,c,d){this.h.remove(String(a),b,c,d)};function Ge(a,b,c,d){b=a.h.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.D&&h.capture==c){var p=h.listener,D=h.L||h.src;h.J&&Nd(a.h,h);e=!1!==p.call(D,d)&&e}}return e&&0!=d.aa}
g.zb=function(a,b){a=this.h.a[String(a).toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};g.Ab=function(a,b){return Pd(this.h,J(a)?String(a):void 0,b)};g.rc=function(a){this.T=a};g.oa=function(){};function X(){}X.a=void 0;X.b=function(){return X.a?X.a:X.a=new X};X.prototype.b=0;X.prototype.a="";X.prototype.c=function(a){this.a=a};function Y(a){Fe.call(this);this.i=a||Nc();this.F=He;this.v=null;this.g=!1;this.a=null;this.l=void 0;this.f=this.b=this.c=this.I=null;this.U=this.N=!1}O(Y,Fe);Y.prototype.da=X.b();var He=null;function Ie(a){var b;(b=a.v)||(b=a.da,b=b.a+":"+(b.b++).toString(36),b=a.v=b);return b}g=Y.prototype;g.mc=function(a){if(this.c&&this.c.f){var b=this.c.f,c=this.v;c in b&&delete b[c];Wa(this.c.f,a,this)}this.v=a};g.o=function(){return this.a};g.Oa=function(){return this.a};
g.Fb=function(a){if(this.a){var b=this.a||this.i.a,c=b||document;a=c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Rc(document,"*",a,b)}else a=[];return a};g.Gb=function(a){return this.a?Pc(a,this.a||this.i.a):null};g.Ta=function(){this.l||(this.l=new te(this));return this.l};
function Je(a,b){if(a==b)throw Error("Unable to set parent component");var c;if(c=b&&a.c&&a.v){c=a.c;var d=a.v;c=c.f&&d?Xa(c.f,d)||null:null}if(c&&a.c!=b)throw Error("Unable to set parent component");a.c=b;Y.w.S.call(a,b)}g.S=function(a){if(this.c&&this.c!=a)throw Error("Method not supported");Y.w.S.call(this,a)};g.O=function(){this.a=V(this.i.a,"DIV")};g.fc=function(a){Ke(this,a.parentNode,a)};
function Ke(a,b,c){if(a.g)throw Error("Component already rendered");a.a||a.O();b?b.insertBefore(a.a,c||null):a.i.a.body.appendChild(a.a);a.c&&!a.c.g||Le(a)}g.ua=function(a){if(this.g)throw Error("Component already rendered");if(a){this.N=!0;var b=U(a);this.i&&this.i.a==b||(this.i=Nc(a));this.a=a;Le(this)}else throw Error("Invalid element to decorate");};g.vc=function(){return this.N};function Le(a){a.g=!0;Me(a,function(b){!b.g&&b.o()&&Le(b)})}
function Ne(a){Me(a,function(b){b.g&&Ne(b)});a.l&&xe(a.l);a.g=!1}g.A=function(){this.g&&Ne(this);this.l&&(this.l.K(),delete this.l);Me(this,function(a){a.K()});!this.N&&this.a&&bd(this.a);this.c=this.I=this.a=this.f=this.b=null;Y.w.A.call(this)};function Oe(a,b){return Ie(a)+"."+b}g.$b=function(a){var b={},c;for(c in a)b[c]=Oe(this,a[c]);return b};g.Wa=function(){return this.I};g.nc=function(a){this.I=a};g.Qa=function(a){return a.substring(Ie(this).length+1)};
g.Ma=function(a){if(!this.g)throw Error("Operation not supported while component is not in document");return this.i.o(Oe(this,a))};
g.na=function(a,b){var c=this.b?this.b.length:0;if(a.g&&(b||!this.g))throw Error("Component already rendered");if(0>c||c>(this.b?this.b.length:0))throw Error("Child component index out of bounds");this.f&&this.b||(this.f={},this.b=[]);if(a.c==this){var d=Ie(a);this.f[d]=a;Da(this.b,a)}else Wa(this.f,Ie(a),a);Je(a,this);Fa(this.b,c,0,a);a.g&&this.g&&a.c==this?(b=this.a,c=b.childNodes[c]||null,c!=a.o()&&b.insertBefore(a.o(),c)):b?(this.a||this.O(),c=this.b?this.b[c+1]||null:null,Ke(a,this.a,c?c.a:null)):
this.g&&!a.g&&a.a&&a.a.parentNode&&1==a.a.parentNode.nodeType&&Le(a)};g.Ub=function(){if(null==this.F){var a=this.g?this.a:this.i.a.body;a:{var b=U(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.direction||b.getPropertyValue("direction")||"";break a}b=""}this.F="rtl"==(b||(a.currentStyle?a.currentStyle.direction:null)||a.style&&a.style.direction)}return this.F};g.qc=function(a){if(this.g)throw Error("Component already rendered");this.F=a};
g.Ga=function(){var a=[];Me(this,function(b){a.push(Ie(b))});return a};function Me(a,b){a.b&&za(a.b,b,void 0)}g.Ib=function(a){return this.b&&a?ya(this.b,a):-1};function Pe(a,b){var c=a.b?a.b[0]||null:null;if(c){var d=K(c)?c:Ie(c);c=a.f&&d?Xa(a.f,d)||null:null;if(d&&c){var e=a.f;d in e&&delete e[d];Da(a.b,c);b&&(Ne(c),c.a&&bd(c.a));Je(c,null)}}if(!c)throw Error("Child is not in parent component");return c}g.Hb=function(a){for(var b=[];this.b&&0!=this.b.length;)b.push(Pe(this,a));return b};g.cc=function(){return this.U};
g.oc=function(a){if(this.g)throw Error("Component already rendered");this.U=a};function Qe(a){Y.call(this,a)}O(Qe,Y);Qe.prototype.O=function(){this.a=this.i.Y("FORM",{method:"POST",style:"display:none"})};function Re(a){var b=new Qe,c=b.o();c||(Ke(b,void 0),c=b.o());c.action="https://jsfiddle.net/api/post/library/pure/";c.target="_blank";Se(b,c,a);c.submit()}function Se(a,b,c){var d,e=[];for(d in c){var f=c[d];qa(f)?za(f,ta(function(h){e.push(Yb({type:"hidden",name:d,value:String(h)}))},a)):e.push(Yb({type:"hidden",name:d,value:String(f)}))}Cc(b,Zb(e))};var Te=["js","html","css"],Ue=!!document.queryCommandSupported("copy");function Z(){var a=uc.call(this,["devsite-snackbar"])||this;a.a=new te;a.b=new Ee;a.i=null;a.f=!1;a.c=null;return a}ia(Z,uc);Z.prototype.X=function(){return"code"};Z.prototype.connectedCallback=function(){vc(this);this.b.get("pref_dark-code")&&this.setAttribute("dark-code","");this.f||(Ve(this),We(this),this.f=!0);Xe(this)};Z.prototype.disconnectedCallback=function(){this.removeChild(this.c);xe(this.a)};
function We(a){Array.from(a.querySelectorAll(".prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;b.innerHTML=window.prettyPrintOne(b.innerHTML,c);b.querySelector("strong")&&b.classList.add("devsite-code-highlight")})}
function Ve(a){var b=a.querySelector("pre");b&&(b.classList.remove("devsite-click-to-copy"),b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy"))&&(a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy"));var c=a.querySelector(".devsite-enable-open-in-jsfiddle");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"));a.hasAttribute("js-fiddle")&&(c&&["scope","jsfiddle-title","jsfiddle-wrap"].forEach(function(d){c.hasAttribute("data-"+
d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))}),b=a.getAttribute("scope"),Array.from(document.querySelectorAll('.devsite-jsfiddle-code-sample[data-scope="'+b+'"]')).forEach(function(d){d.parentNode!==a&&a.appendChild(d)}))}
Z.prototype.attributeChangedCallback=function(a,b,c){"dark-code"===a&&b!==c&&(this.hasAttribute("dark-code")?(this.b.set("pref_dark-code","1"),window.requestAnimationFrame(function(){Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).forEach(function(d){d.setAttribute("dark-code","")})})):(this.b.remove("pref_dark-code"),window.requestAnimationFrame(function(){Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(d){d.removeAttribute("dark-code")})})))};
function Xe(a){var b=ye(pc);if(a.hasAttribute("scope")){var c=ye(tc);a.a.u(c,"click",function(){Ye(a)});a.hasAttribute("jsfiddle-title")&&c.setAttribute("data-label",a.getAttribute("jsfiddle-title"));b.appendChild(c)}c=ye(qc);a.a.u(c,"click",function(){a.setAttribute("dark-code","")});var d=ye(rc);a.a.u(d,"click",function(){a.removeAttribute("dark-code")});if(!a.hasAttribute("no-copy")&&Ue){var e=ye(sc);a.a.u(e,"click",function(){var f=Array.from(a.querySelectorAll("pre"));wd(a,f)});b.appendChild(e)}b.appendChild(c);
b.appendChild(d);a.appendChild(b);a.c=b;a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))}function Ye(a){var b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""};Te.forEach(function(c){Array.from(a.querySelectorAll('[data-type="'+c+'"]')).forEach(function(d){d=td(a,d);var e=ud(d);window.getSelection().removeAllRanges();bd(d);b[c]=b[c]?b[c]+("\n"+e):e})});Re(b)}
ja.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-code",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};}).call(this);
